name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract git commit hash
      id: vars
      run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

    - name: Build Docker image
      run: |
        docker build -t my-dockerhub-username/rcl-demo:latest -t my-dockerhub-username/rcl-demo:${{ steps.vars.outputs.sha }} .

    - name: Push Docker image to Docker Hub
      run: |
        docker push my-dockerhub-username/rcl-demo:latest
        docker push my-dockerhub-username/rcl-demo:${{ steps.vars.outputs.sha }}
